import type { AnalysisResult, SystemModel } from "../../shared/schemas.js";

function download(name: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}

function safeName(name: string): string {
  return name
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/(^-|-$)/g, "");
}

export function exportModel(model: SystemModel): void {
  download(
    `${safeName(model.name)}.argus.json`,
    `${JSON.stringify(model, null, 2)}\n`,
    "application/json",
  );
}

export function exportAnalysisJson(model: SystemModel, result: AnalysisResult): void {
  download(
    `${safeName(model.name)}-threat-model.json`,
    `${JSON.stringify({ model, analysis: result }, null, 2)}\n`,
    "application/json",
  );
}

export function buildMarkdown(model: SystemModel, result: AnalysisResult): string {
  const lines = [
    `# ${model.name} — threat model`,
    "",
    `Generated by Argus engine ${result.engineVersion} on ${new Date(result.generatedAt).toLocaleString()}.`,
    "",
    "## Scope",
    "",
    model.description || "No description supplied.",
    "",
    `- Analysis mode: ${result.mode}`,
    `- Business criticality: ${model.businessCriticality}`,
    `- Components: ${model.nodes.length}`,
    `- Data flows: ${model.flows.length}`,
    "",
    "## Summary",
    "",
    `- Total threats: ${result.summary.total}`,
    `- Critical: ${result.summary.critical}`,
    `- High: ${result.summary.high}`,
    `- Medium: ${result.summary.medium}`,
    `- Low: ${result.summary.low}`,
    `- Recommended controls: ${result.summary.controlCount}`,
    "",
    "## Prioritised threats",
    "",
  ];

  for (const [index, threat] of result.threats.entries()) {
    lines.push(
      `### ${index + 1}. ${threat.title}`,
      "",
      `**Risk:** ${threat.severity.toUpperCase()} (${threat.riskScore}/100)  `,
      `**Type:** ${threat.findingType}  `,
      `**Confidence:** ${threat.confidence}`,
      "",
      threat.scenario,
      "",
      `**Attack path:** ${threat.attackPath.join(" → ")}`,
      "",
      `**Frameworks:** ${threat.frameworks.map((item) => `${item.framework} ${item.id}`).join(", ") || "None"}`,
      "",
      `**Controls:** ${threat.controlIds.join(", ")}`,
      "",
    );
  }

  lines.push("## Control plan", "");
  for (const control of result.controls) {
    lines.push(
      `### ${control.id}: ${control.title}`,
      "",
      `${control.priority.toUpperCase()} · ${control.type}`,
      "",
      control.objective,
      "",
      "Implementation:",
      ...control.implementation.map((item) => `- ${item}`),
      "",
      "Verification:",
      ...control.verification.map((item) => `- ${item}`),
      "",
    );
  }

  lines.push(
    "## Interpretation warnings",
    "",
    ...result.warnings.map((warning) => `- ${warning}`),
    "",
  );
  return lines.join("\n");
}

export function exportAnalysisMarkdown(model: SystemModel, result: AnalysisResult): void {
  download(
    `${safeName(model.name)}-threat-model.md`,
    buildMarkdown(model, result),
    "text/markdown",
  );
}
